source 'https://rubygems.org'


gem 'rails', '4.1.5'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer',  platforms: :ruby
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'haml', '~> 4.0.6'
gem 'execjs', '~> 2.4.0'
gem 'turbolinks'
gem 'simple_form', '~> 3.1.0'
gem 'bootstrap-sass', '~> 3.3.4'
gem 'paperclip', '~> 4.2.1'
gem 'cocoon', '~> 1.2.6'
gem 'devise', '~> 3.4.1'
